### ISSUE TITLE
[Issue] Incorrect captchas 

### ISSUE THREAD

**Issue by uzair004** [infosimples/node_two_captcha#10]
I am trying to solve image-based captchas using this library, I also have funds in a 2captcha account.
Getting completely irrelevant & mismatch captchas suggestions.

letters aren't even close to the challenge, I am suspicious if 2captcha is scam or using bot to just reply with random characters.

**Comment by barbolo** [comment]
I'm sorry to hear that. However the team responsible for this GitHub project can't do anything about it, since we don't work at 2Captcha. You can probably get in touch with them to understand what is happening.
